package com.payement.wallet.Enum;

public enum ErrorCode {
    ACCCOUNT_NOT_FOUND,
    INSUFFICIENT_BALANCE,
    INVALID_AMOUNT,
    INVALID_ACCOUNT_NUMBER,
    TRANSACTION_FAILED,
    UNKNOWN_ERROR,
    USER_NOT_FOUND,
    INVALID_CREDENTIALS,
    VALIDATION_ERROR,
    CONSTRAINT_VIOLATION
}
